type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table "
        - "SQL Script"
      parameters:
        componentName: "Start"
    'Create Table ':
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table "
        createMethod: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "DEMOGRAPHIC"
        snowflakeTableType: "Permanent"
        columns:
        - - "CustomerID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "LastName"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "FirstName"
          - "VARCHAR"
          - "60"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "BirthDate"
          - "DATE"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Gender"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "ParticipantType"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "RegionID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "MaritalStatus"
          - "VARCHAR"
          - "15"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://analytics06/customerdata/CUSTOMER.csv"
        pattern: ".*.csv"
        encryption: "None"
        warehouse: "DEMOWAREHOUSE"
        database: "DEMODATABASE"
        schema: "DEMOSCHEMA"
        targetTable: "DEMOGRAPHIC"
        loadColumns:
        - "CustomerID"
        - "LastName"
        - "FirstName"
        - "BirthDate"
        - "Gender"
        - "ParticipantType"
        - "RegionID"
        - "MaritalStatus"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "True"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "True"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Continue"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script:
      type: "sql-executor"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "DELETE FROM\r\nDEMODATABASE.DEMOSCHEMA.DEMOGRAPHIC\r\nWHERE 'MaritalStatus'=\r\
          \n'Divorced'\r\n"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -20
        "y": 10
      tempMetlId: 1
    'Create Table ':
      position:
        x: 160
        "y": 10
      tempMetlId: 3
    S3 Load:
      position:
        x: 330
        "y": 10
      tempMetlId: 4
    SQL Script:
      position:
        x: 140
        "y": -110
      tempMetlId: 5
