type: "orchestration"
version: "1.0"
pipeline:
  metadata:
    description: "Orchestration job with parameters to extract data from Src to stg\
      \ and then stg to target"
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Fixed Iterator 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Extract_from_Source 0:
      type: "run-orchestration"
      skipped: false
      parameters:
        componentName: "Extract_from_Source 0"
        orchestrationJob: "Classwork/Project2_comman/V2_2Extract_basedon_loadtype2"
        setScalarVariables:
        - - "JV_DB"
          - "${JV_DB}"
        - - "JV_TABLE_NAME"
          - "${JV_TABLE_NAME}"
        - - "JV_SCHEMA"
          - "${JV_SCHEMA}"
        - - "JV_LOADTYPE"
          - "${JV_LOADTYPE}"
        setGridVariables:
    Grid Iterator 0:
      type: "grid-iterator"
      transitions:
        success:
        - "SNS Success"
        failure:
        - "SNS EXTRACTION Failure"
        unconditional:
        - "v2_5_transformation"
      iterationTarget: "Extract_from_Source 0"
      skipped: false
      parameters:
        componentName: "Grid Iterator 0"
        gridVariable: "GRID_VAR_TBL_LOADTYPE"
        gridIteratorVariableMapping:
        - - "TABLE_NAME"
          - "JV_TABLE_NAME"
        - - "LOAD_TYPE"
          - "JV_LOADTYPE"
        breakOnFailure: "No"
        concurrency: "Sequential"
    SNS EXTRACTION Failure:
      type: "sns-message"
      transitions:
        unconditional:
        - "End Failure"
      skipped: false
      parameters:
        componentName: "SNS EXTRACTION Failure"
        awsRegion: "eu-north-1"
        topicName: "Matillion_Status"
        subject: "AWS Notification SNS Grid iterator"
        message: |
          Needs attention!!! Job failed :-(


          JOB ID:${job_id}
          JOB NAME: ${sysvar.thisPipeline.fullName}
          MESSAGE:${sysvar.thisComponent.message}
          DETAILED ERROR:${detailed_error}
    End Failure:
      type: "end-failure"
      skipped: false
      parameters:
        componentName: "End Failure"
    End Success:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success"
    SNS Failure:
      type: "sns-message"
      skipped: false
      parameters:
        componentName: "SNS Failure"
        awsRegion: "eu-north-1"
        topicName: "Matillion_Status"
        subject: "AWS Notification SNS Grid iterator"
        message: |
          Needs attention!!! Job failed :-(


          JOB ID:${job_id}
          JOB NAME: ${sysvar.thisPipeline.fullName}
          MESSAGE:${sysvar.thisComponent.message}
          DETAILED ERROR:${detailed_error}
    S3 Load:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load"
        stage: "Matillion_Stage"
        pattern: "${file_name}.csv "
        warehouse: "MATILLION_PRG"
        database: "RESTAURANTSALES"
        schema: "RESTAURANT_DB"
        targetTable: "${file_name.replace(/\"/g,'')}"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "True"
        metadataFields:
    Fixed Iterator 0:
      type: "fixed-iterator"
      transitions:
        success:
        - "End Success 0"
        failure:
        - "End Failure 0"
        unconditional:
        - "Query Result (Matadata) To Grid"
      iterationTarget: "S3 Load"
      skipped: false
      parameters:
        componentName: "Fixed Iterator 0"
        concurrency: "Sequential"
        variablesToIterate:
        - "file_name"
        iterationValues:
        - - "MENU_ITEMS"
        - - "ORDER_DETAILS"
        breakOnFailure: "No"
    Query Result (Matadata) To Grid:
      type: "query-to-grid"
      transitions:
        unconditional:
        - "Python Script 0"
      skipped: false
      parameters:
        componentName: "Query Result (Matadata) To Grid"
        mode: "Advanced"
        query: "/* Note: this query will be run as a subquery for the purposes of\
          \ sampling the data.\n\n   As such it will be restricted by any subquery\
          \ limitations specified by the current platform. */\n   \n   SELECT \nUPPER(TABLE_NAME)\
          \ TABLE_NAME,UPPER(LOAD_TYPE) LOAD_TYPE,IS_ACTIVE\nFROM \nRESTAURANTSALES.RESTAURANT_METADATA.TABLE_LOAD_METADATA\n\
          WHERE IS_ACTIVE =1"
        gridVariable: "GRID_VAR_TBL_LOADTYPE"
        gridVariableMapping:
        - - "TABLE_NAME"
          - "TABLE_NAME"
        - - "LOAD_TYPE"
          - "LOAD_TYPE"
    Python Script 0:
      type: "python-script"
      transitions:
        unconditional:
        - "Grid Iterator 0"
      skipped: false
      parameters:
        componentName: "Python Script 0"
        script: "###\n# Variables are directly accessible: \n#   print (myvar)\n#\
          \ Updating a variable:\n#   context.updateVariable('myvar', 'new-value')\n\
          # Grid Variables are accessible via the context:\n#   print (context.getGridVariable('mygridvar'))\n\
          # Updating a grid variable:\n#   context.updateGridVariable('mygridvar',\
          \ [['list','of'],['lists','!']])\n# A database cursor can be accessed from\
          \ the context (Jython only):\n#   cursor = context.cursor()\n#   cursor.execute('select\
          \ count(*) from mytable')\n#   rowcount = cursor.fetchone()[0]\n###\nprint\
          \ (context.getGridVariable('GRID_VAR_TBL_LOADTYPE'))\nprint(JV_TABLE_NAME)\n\
          print (JV_LOADTYPE)"
        interpreter: "Python 3"
        timeout: "360"
    SNS Success:
      type: "sns-message"
      transitions:
        unconditional:
        - "End Success"
      skipped: false
      parameters:
        componentName: "SNS Success"
        awsRegion: "eu-north-1"
        topicName: "Matillion_Status"
        subject: "AWS Notification Message"
        message: |+
          EXTRACTION AND CLEANING SUCCESSFULLY COMPLETED
          JOB ID:${job_id}
          JOB NAME: ${sysvar.thisPipeline.fullName}
          MESSAGE:${sysvar.thisComponent.message}

    v2_5_transformation:
      type: "run-transformation"
      transitions:
        success:
        - "SNS Message 0"
        failure:
        - "SNS Failure"
      skipped: false
      parameters:
        componentName: "v2_5_transformation"
        transformationJob: "Classwork/Project2_comman/v2_5_transformation"
        setScalarVariables:
        setGridVariables:
    SNS Message 0:
      type: "sns-message"
      skipped: false
      parameters:
        componentName: "SNS Message 0"
        awsRegion: "eu-north-1"
        topicName: "Matillion_Status"
        subject: "AWS Notification Message"
        message: |+
          JOB SUCCESSFULLY COMPLETED
          JOB ID:${job_id}
          JOB NAME: ${sysvar.thisPipeline.fullName}
          MESSAGE:${sysvar.thisComponent.message}

    End Failure 0:
      type: "end-failure"
      skipped: false
      parameters:
        componentName: "End Failure 0"
    End Success 0:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success 0"
  variables:
    JV_DB:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "RESTAURANTSALES"
    JV_SCHEMA:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "RESTAURANT_DB"
    file_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MENU_ITEMS"
    JV_LOADTYPE:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "I"
    JV_TABLE_NAME:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "ORDER_DETAILS"
    dictionary_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Mat_Tableinput"
    GRID_VAR_TBL_LOADTYPE:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          TABLE_NAME:
            columnType: "TEXT"
          LOAD_TYPE:
            columnType: "TEXT"
      defaultValue:
      - - "MENU_ITEMS"
        - "R"
    GRID_INTIAL_TABLE_NAME:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          Columnname:
            columnType: "TEXT"
      defaultValue:
      - - "menu_item_id"
      - - "item_name"
      - - "category"
      - - "price"
design:
  components:
    Start 0:
      position:
        x: -784
        "y": 0
      tempMetlId: 845
    Extract_from_Source 0:
      position:
        x: -171
        "y": 2
      tempMetlId: 846
    Grid Iterator 0:
      position:
        x: -171
        "y": 2
      tempMetlId: 847
    SNS EXTRACTION Failure:
      position:
        x: -176
        "y": 112
      tempMetlId: 848
    End Failure:
      position:
        x: -176
        "y": 208
      tempMetlId: 849
    End Success:
      position:
        x: -176
        "y": -144
      tempMetlId: 850
    SNS Failure:
      position:
        x: 272
        "y": 112
      tempMetlId: 851
    S3 Load:
      position:
        x: -624
        "y": 32
      tempMetlId: 852
    Fixed Iterator 0:
      position:
        x: -624
        "y": 0
      tempMetlId: 853
    Query Result (Matadata) To Grid:
      position:
        x: -480
        "y": 0
      tempMetlId: 896
    Python Script 0:
      position:
        x: -304
        "y": 0
      tempMetlId: 897
    SNS Success:
      position:
        x: -176
        "y": -64
      tempMetlId: 898
    v2_5_transformation:
      position:
        x: 32
        "y": 0
      tempMetlId: 899
    SNS Message 0:
      position:
        x: 272
        "y": -64
      tempMetlId: 900
    End Failure 0:
      position:
        x: -624
        "y": 144
      tempMetlId: 5964
    End Success 0:
      position:
        x: -624
        "y": -128
      tempMetlId: 5968
